#import subprocess is used to run the text output generated in the ubuntu command line
import subprocess

#This script doest the following: 1) Conserve the header from vitis_vinifera_nr_go_table_clean_BP_ancestor.tsv,
#2) fetch only the DEG (up and downregulated separetely) with grep, and split the ancestor list by each treatment upregulated and downregulated

#elements from this script: up_down_list.txt contains a list .txt file names, each containing the upregulated and downregulated genes, separately, for each treatment
#vitis_vinifera_nr_go_table_clean_BP_ancestor.tsv is the list of GO terms from blast2go annotation with all the corresponding ancestor GO, generated by fetch_ancestors.R
for up_down_term in open('up_down_list.txt'):
    up_down_term = up_down_term.strip()

    # Build the full command
    command = f"(head -n 1 vitis_vinifera_nr_go_table_clean_BP_ancestor.tsv && grep -f {up_down_term} vitis_vinifera_nr_go_table_clean_BP_ancestor.tsv) > vitis_vinifera_go_table_BP_ancestor_{up_down_term}"

    # Execute the command using subprocess
    subprocess.run(command, shell=True)

    print(f"Command executed for {up_down_term}. Output saved to vitis_vinifera_go_table_BP_ancestor_{up_down_term}.txt")
